build and push into DockerHub

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -12,36 +12,29 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      - name: Build Docker image
-        run: |
-          docker build . \
-            --file Dockerfile \
-            --tag my-image-name:latest
+      - name: Login to Docker Hub
+        uses: docker/login-action@v4
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-      - name: Check Docker image
-        run: |
-          docker images
+      - name: Build and push
+        uses: docker/build-push-action@v7
+        with:
+          context: .
+          push: true
+          tags: riteshp777/ciworkflow:latest
+      - name: run container
+        run: docker run -d -p 4000:4000 --name container riteshp777/ciworkflow:latest
 
-      - name: Run Docker container
+      - name: Test the application
         run: |
-          docker run -d \
-            -p 4000:4000 \
-            --name container \
-            my-image-name:latest
+          sleep 5 # Wait for the container to start
+          response=$(curl -s http://localhost:4000)
+          if [[ "$response" == "Hello, World!" ]]; then
+            echo "Test passed!"
+          else
+            echo "Test failed!"
+            exit 1
+          fi  
 
-      - name: Check container status
-        run: |
-          docker ps
-          docker ps -a
-
-      - name: Check container logs
-        run: |
-          docker logs container
-
-      - name: Wait for application
-        run: |
-          sleep 10
-
-      - name: Test application
-        run: |
-          curl -v http://localhost:4000
